# pytest.ini
[pytest]
python_files = *_tests.py test_*.py  # Это мы добавили в предыдущем шаге
python_classes = Test*               # Устанавливает правила для имен классов
python_functions = test_*            # Устанавливает правила для имен функций

markers =
    regression: Маркировка для регрессионных тестов.
    registration: Маркировка для тестов, связанных с регистрацией пользователей.
    authorization: Маркировака для тестов, связанных с авторизацие пользователей.
    ui: Маркировка для тестов, связанных с UI.
    smoke: Маркировка для смоук тестов.
    critical: Маркировка для критически важных тестов.
    slow: Маркировка для медленных тестов.
    courses: Маркировка для тестов, написанных в рамках курса.
    dashboard: Маркировка для тестов, связанных с рабочей панелью.
